export const ActionTypes = {
    SET_GAMES: 'SET_GAMES',
    SET_GAMES_FROM_DB: 'SET_GAMES_FROM_DB',
    ADD_GAMES: 'ADD_GAMES',
    SET_TAGS: 'SET_TAGS',
    SET_GENRES: 'SET_GENRES',
    SET_ALL_GAMES: 'SET_ALL_GAMES',
    SET_SINGLE_GAME: 'SET_SINGLE_GAME',
    SET_PLATFORM: 'SET_PLATFORM',
    SET_SEARCH_GAMES: 'SET_SEARCH_GAMES',
    SET_USERNAME: 'SET_USERNAME',
    FAILED_REGISTERATION: 'FAILED_REGISTERATION',
    SET_FAVOURITE_GAMES: 'SET_FAVOURITE_GAMES',
    ADD_FAVOURITE_GAMES: 'SET_FAVOURITE_GAMES',
    REMOVE_FAVOURITE_GAMES: 'SET_FAVOURITE_GAMES',
    ADD_USER_FAVOURITE: 'ADD_USER_FAVOURITE',
    SET_USER_ADDED_GAMES: "SET_USER_ADDED_GAMES"
}